# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.TextField()),
                ('service', models.TextField()),
                ('sev', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_num', models.IntegerField()),
                ('month_name', models.TextField()),
                ('month_code', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.DecimalField(decimal_places=4, max_digits=5)),
                ('duration', models.DecimalField(decimal_places=5, max_digits=12)),
                ('mttr', models.DecimalField(decimal_places=5, max_digits=12)),
                ('count', models.IntegerField()),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('year', models.IntegerField()),
                ('week_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='uptime',
            name='week_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Week'),
        ),
    ]
