# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uptime',
            new_name='Uptime_Week',
        ),
    ]
