# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20171023_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uptime_week',
            name='mttr',
        ),
        migrations.RemoveField(
            model_name='uptime_week',
            name='uptime',
        ),
    ]
