# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('uni_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
