# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='last_run',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='script',
            name='last_run_comp',
            field=models.BooleanField(default=False),
        ),
    ]
