# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('comp', models.BooleanField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripts.Script')),
            ],
        ),
    ]
